// <auto-generated />
using System;
using CourseRegistrationNew.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseRegistrationNew.Migrations
{
    [DbContext(typeof(DbContextCourse))]
    partial class DbContextCourseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CourseRegistrationNew.Models.CoursesStudents", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int?>("CoursesCourseID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int?>("StudentsStudentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CoursesCourseID");

                    b.HasIndex("StudentsStudentID");

                    b.ToTable("CoursesStudents");
                });

            modelBuilder.Entity("CourseRegistrationProgram.Models.Courses", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CourseDescription")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CourseName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CourseNumber")
                        .HasColumnType("text");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CourseRegistrationProgram.Models.Instructors", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Course")
                        .HasColumnType("text");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int?>("CoursesCourseID")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("InstructorId");

                    b.HasIndex("CoursesCourseID");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("CourseRegistrationProgram.Models.Students", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("StudentID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CourseRegistrationNew.Models.CoursesStudents", b =>
                {
                    b.HasOne("CourseRegistrationProgram.Models.Courses", null)
                        .WithMany("StudentsList")
                        .HasForeignKey("CoursesCourseID");

                    b.HasOne("CourseRegistrationProgram.Models.Students", null)
                        .WithMany("CoursesList")
                        .HasForeignKey("StudentsStudentID");
                });

            modelBuilder.Entity("CourseRegistrationProgram.Models.Instructors", b =>
                {
                    b.HasOne("CourseRegistrationProgram.Models.Courses", "Courses")
                        .WithMany("Instructors")
                        .HasForeignKey("CoursesCourseID");
                });
#pragma warning restore 612, 618
        }
    }
}
